[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "q8020-cfd-metautil"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib",
    "numpy",
    "duckdb",
    "streamlit",
    "plotly",
    "watchdog",
    "subprocess-tee"
]

[project.scripts]
q8020-sweep = "q8020_cfd_metautil.sweep:main"
q8020-sweeper = "q8020_cfd_metautil.sweep:main"
q8020-harvest = "q8020_cfd_metautil.harvest:main"
# q8020-compare = "q8020_cfd_metautil.compare:main"
q8020-metakeys = "q8020_cfd_metautil.metakeys:main"
q8020-corpus-ingest = "q8020_cfd_metautil.corpus.ingest:main"
q8020-corpus-viz = "q8020_cfd_metautil.corpus.viz:main"


[tool.setuptools.packages.find]
where = ["src"]

[tool.pylint.messages_control]
disable = [
    "C0103",  # invalid-name
    "C0305",  # trailing-newlines
    "C0303",  # trailing-whitespace
    "C0301",  # line-too-long
    "W0621",  # redefined-outer-name
]
