[metadata]
name = q8020-cfd-metautil
version = 0.1.0

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.12,<3.13
install_requires =
    matplotlib
    numpy
    duckdb
    streamlit
    plotly
    watchdog
    subprocess-tee

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    q8020-sweep = q8020_cfd_metautil.sweep:main
    q8020-harvest = q8020_cfd_metautil.harvest:main
    q8020-metakeys = q8020_cfd_metautil.metakeys:main
