# FVM Euler 1D Solver - example invocation via q8020-sweeper 

[global]
_output_dir = "~/q8020"
_env = "./fvm_euler_1d_solver/.venv"
_script = """\
source ./fvm_euler_1d_solver/.venv/bin/activate && \
python ./fvm_euler_1d_solver/nozzle_1d_solver.py\
"""
_case_postproc = [
    "python -m q8020_cfd_metautil.harvesters.fvm_euler_1d_solver_harvester"
]
_inject_outdir = "-outdir"
"-nelem" = 2
"-time_scheme" = "BDF1"
"-linsolver" = "HHL"
"-localdt" = true
"-noshow" = true

[ideal]

[shots]
"-shots" = 1024 

[fake_real]
"-backend" = "fake fake_guadalupe"
"-shots" = 1024 





